require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DependentsController do

  # This should return the minimal set of attributes required to create a valid
  # Dependent. As you add validations to Dependent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DependentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dependents as @dependents" do
      dependent = Dependent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dependents).should eq([dependent])
    end
  end

  describe "GET show" do
    it "assigns the requested dependent as @dependent" do
      dependent = Dependent.create! valid_attributes
      get :show, {:id => dependent.to_param}, valid_session
      assigns(:dependent).should eq(dependent)
    end
  end

  describe "GET new" do
    it "assigns a new dependent as @dependent" do
      get :new, {}, valid_session
      assigns(:dependent).should be_a_new(Dependent)
    end
  end

  describe "GET edit" do
    it "assigns the requested dependent as @dependent" do
      dependent = Dependent.create! valid_attributes
      get :edit, {:id => dependent.to_param}, valid_session
      assigns(:dependent).should eq(dependent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dependent" do
        expect {
          post :create, {:dependent => valid_attributes}, valid_session
        }.to change(Dependent, :count).by(1)
      end

      it "assigns a newly created dependent as @dependent" do
        post :create, {:dependent => valid_attributes}, valid_session
        assigns(:dependent).should be_a(Dependent)
        assigns(:dependent).should be_persisted
      end

      it "redirects to the created dependent" do
        post :create, {:dependent => valid_attributes}, valid_session
        response.should redirect_to(Dependent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dependent as @dependent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dependent.any_instance.stub(:save).and_return(false)
        post :create, {:dependent => { "name" => "invalid value" }}, valid_session
        assigns(:dependent).should be_a_new(Dependent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dependent.any_instance.stub(:save).and_return(false)
        post :create, {:dependent => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dependent" do
        dependent = Dependent.create! valid_attributes
        # Assuming there are no other dependents in the database, this
        # specifies that the Dependent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dependent.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => dependent.to_param, :dependent => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested dependent as @dependent" do
        dependent = Dependent.create! valid_attributes
        put :update, {:id => dependent.to_param, :dependent => valid_attributes}, valid_session
        assigns(:dependent).should eq(dependent)
      end

      it "redirects to the dependent" do
        dependent = Dependent.create! valid_attributes
        put :update, {:id => dependent.to_param, :dependent => valid_attributes}, valid_session
        response.should redirect_to(dependent)
      end
    end

    describe "with invalid params" do
      it "assigns the dependent as @dependent" do
        dependent = Dependent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dependent.any_instance.stub(:save).and_return(false)
        put :update, {:id => dependent.to_param, :dependent => { "name" => "invalid value" }}, valid_session
        assigns(:dependent).should eq(dependent)
      end

      it "re-renders the 'edit' template" do
        dependent = Dependent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dependent.any_instance.stub(:save).and_return(false)
        put :update, {:id => dependent.to_param, :dependent => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dependent" do
      dependent = Dependent.create! valid_attributes
      expect {
        delete :destroy, {:id => dependent.to_param}, valid_session
      }.to change(Dependent, :count).by(-1)
    end

    it "redirects to the dependents list" do
      dependent = Dependent.create! valid_attributes
      delete :destroy, {:id => dependent.to_param}, valid_session
      response.should redirect_to(dependents_url)
    end
  end

end
