require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForPagsController do

  # This should return the minimal set of attributes required to create a valid
  # ForPag. As you add validations to ForPag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForPagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all for_pags as @for_pags" do
      for_pag = ForPag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:for_pags).should eq([for_pag])
    end
  end

  describe "GET show" do
    it "assigns the requested for_pag as @for_pag" do
      for_pag = ForPag.create! valid_attributes
      get :show, {:id => for_pag.to_param}, valid_session
      assigns(:for_pag).should eq(for_pag)
    end
  end

  describe "GET new" do
    it "assigns a new for_pag as @for_pag" do
      get :new, {}, valid_session
      assigns(:for_pag).should be_a_new(ForPag)
    end
  end

  describe "GET edit" do
    it "assigns the requested for_pag as @for_pag" do
      for_pag = ForPag.create! valid_attributes
      get :edit, {:id => for_pag.to_param}, valid_session
      assigns(:for_pag).should eq(for_pag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForPag" do
        expect {
          post :create, {:for_pag => valid_attributes}, valid_session
        }.to change(ForPag, :count).by(1)
      end

      it "assigns a newly created for_pag as @for_pag" do
        post :create, {:for_pag => valid_attributes}, valid_session
        assigns(:for_pag).should be_a(ForPag)
        assigns(:for_pag).should be_persisted
      end

      it "redirects to the created for_pag" do
        post :create, {:for_pag => valid_attributes}, valid_session
        response.should redirect_to(ForPag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved for_pag as @for_pag" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForPag.any_instance.stub(:save).and_return(false)
        post :create, {:for_pag => { "description" => "invalid value" }}, valid_session
        assigns(:for_pag).should be_a_new(ForPag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForPag.any_instance.stub(:save).and_return(false)
        post :create, {:for_pag => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested for_pag" do
        for_pag = ForPag.create! valid_attributes
        # Assuming there are no other for_pags in the database, this
        # specifies that the ForPag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForPag.any_instance.should_receive(:update).with({ "description" => "MyString" })
        put :update, {:id => for_pag.to_param, :for_pag => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested for_pag as @for_pag" do
        for_pag = ForPag.create! valid_attributes
        put :update, {:id => for_pag.to_param, :for_pag => valid_attributes}, valid_session
        assigns(:for_pag).should eq(for_pag)
      end

      it "redirects to the for_pag" do
        for_pag = ForPag.create! valid_attributes
        put :update, {:id => for_pag.to_param, :for_pag => valid_attributes}, valid_session
        response.should redirect_to(for_pag)
      end
    end

    describe "with invalid params" do
      it "assigns the for_pag as @for_pag" do
        for_pag = ForPag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForPag.any_instance.stub(:save).and_return(false)
        put :update, {:id => for_pag.to_param, :for_pag => { "description" => "invalid value" }}, valid_session
        assigns(:for_pag).should eq(for_pag)
      end

      it "re-renders the 'edit' template" do
        for_pag = ForPag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForPag.any_instance.stub(:save).and_return(false)
        put :update, {:id => for_pag.to_param, :for_pag => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested for_pag" do
      for_pag = ForPag.create! valid_attributes
      expect {
        delete :destroy, {:id => for_pag.to_param}, valid_session
      }.to change(ForPag, :count).by(-1)
    end

    it "redirects to the for_pags list" do
      for_pag = ForPag.create! valid_attributes
      delete :destroy, {:id => for_pag.to_param}, valid_session
      response.should redirect_to(for_pags_url)
    end
  end

end
