require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SonsController do

  # This should return the minimal set of attributes required to create a valid
  # Son. As you add validations to Son, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SonsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sons as @sons" do
      son = Son.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sons).should eq([son])
    end
  end

  describe "GET show" do
    it "assigns the requested son as @son" do
      son = Son.create! valid_attributes
      get :show, {:id => son.to_param}, valid_session
      assigns(:son).should eq(son)
    end
  end

  describe "GET new" do
    it "assigns a new son as @son" do
      get :new, {}, valid_session
      assigns(:son).should be_a_new(Son)
    end
  end

  describe "GET edit" do
    it "assigns the requested son as @son" do
      son = Son.create! valid_attributes
      get :edit, {:id => son.to_param}, valid_session
      assigns(:son).should eq(son)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Son" do
        expect {
          post :create, {:son => valid_attributes}, valid_session
        }.to change(Son, :count).by(1)
      end

      it "assigns a newly created son as @son" do
        post :create, {:son => valid_attributes}, valid_session
        assigns(:son).should be_a(Son)
        assigns(:son).should be_persisted
      end

      it "redirects to the created son" do
        post :create, {:son => valid_attributes}, valid_session
        response.should redirect_to(Son.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved son as @son" do
        # Trigger the behavior that occurs when invalid params are submitted
        Son.any_instance.stub(:save).and_return(false)
        post :create, {:son => { "name" => "invalid value" }}, valid_session
        assigns(:son).should be_a_new(Son)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Son.any_instance.stub(:save).and_return(false)
        post :create, {:son => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested son" do
        son = Son.create! valid_attributes
        # Assuming there are no other sons in the database, this
        # specifies that the Son created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Son.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => son.to_param, :son => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested son as @son" do
        son = Son.create! valid_attributes
        put :update, {:id => son.to_param, :son => valid_attributes}, valid_session
        assigns(:son).should eq(son)
      end

      it "redirects to the son" do
        son = Son.create! valid_attributes
        put :update, {:id => son.to_param, :son => valid_attributes}, valid_session
        response.should redirect_to(son)
      end
    end

    describe "with invalid params" do
      it "assigns the son as @son" do
        son = Son.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Son.any_instance.stub(:save).and_return(false)
        put :update, {:id => son.to_param, :son => { "name" => "invalid value" }}, valid_session
        assigns(:son).should eq(son)
      end

      it "re-renders the 'edit' template" do
        son = Son.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Son.any_instance.stub(:save).and_return(false)
        put :update, {:id => son.to_param, :son => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested son" do
      son = Son.create! valid_attributes
      expect {
        delete :destroy, {:id => son.to_param}, valid_session
      }.to change(Son, :count).by(-1)
    end

    it "redirects to the sons list" do
      son = Son.create! valid_attributes
      delete :destroy, {:id => son.to_param}, valid_session
      response.should redirect_to(sons_url)
    end
  end

end
